// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7t5YHdKfe8OC4gJbrpzjhdpAeHMLQE_0',
    appId: '1:192302012220:web:c414dfc03a8cd07c1f3039',
    messagingSenderId: '192302012220',
    projectId: 'test-samples-670b3',
    authDomain: 'test-samples-670b3.firebaseapp.com',
    databaseURL: 'https://test-samples-670b3.firebaseio.com',
    storageBucket: 'test-samples-670b3.appspot.com',
    measurementId: 'G-VPXHHPLEC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdQgS6LujVPBuuzYkw6gwpFKQhIFiap28',
    appId: '1:192302012220:android:364c4a22a09d0e101f3039',
    messagingSenderId: '192302012220',
    projectId: 'test-samples-670b3',
    databaseURL: 'https://test-samples-670b3.firebaseio.com',
    storageBucket: 'test-samples-670b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZKwpaqRhxHcT9f8HfWew1NNw__bSANvE',
    appId: '1:192302012220:ios:70f32695d0be369e1f3039',
    messagingSenderId: '192302012220',
    projectId: 'test-samples-670b3',
    databaseURL: 'https://test-samples-670b3.firebaseio.com',
    storageBucket: 'test-samples-670b3.appspot.com',
    iosClientId: '192302012220-u5vbe8443v9thpd4md9ofov849m5mfjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.issue',
  );
}
